<Project>
    <PropertyGroup>
        <!-- Keep in sync with WS4WSetupScript.iss and VersionInfo.xml -->
        <AssemblyVersion>1.7.2.0</AssemblyVersion>
        <FileVersion>1.7.2.0</FileVersion>
        <InformationalVersion>1.7.2.0</InformationalVersion>
        <Authors>Patrick Gnehm; Micah Morrison</Authors>
        <Product>Wireguard Server</Product>
    </PropertyGroup>
</Project>
