<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Images\logo.ico</ApplicationIcon>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
    <PackageId>WS4W</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\cancel.png" />
    <None Remove="Images\checked.png" />
    <None Remove="Images\info.png" />
    <None Remove="Images\logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CalcBinding" Version="2.5.2" />
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="Humanizer.Core" Version="3.0.10" />
    <PackageReference Include="Microsoft.WindowsAPICodePack-Core" Version="1.1.0.2" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
    <PackageReference Include="sharpconfig" Version="4.1.0" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WireGuardAPI\WireGuardAPI.csproj" />
    <ProjectReference Include="..\WireGuardServerForWindows.Cli.Options\WireGuardServerForWindows.Cli.Options.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\cancel.png" />
    <Resource Include="Images\checked.png" />
    <Resource Include="Images\info.png" />
    <Resource Include="Images\logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <CustomToolNamespace>WireGuardServerForWindows.Properties</CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>

</Project>
